### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-1-beatrizsobrinoparedes#2]
Muy buen trabajo!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Score: 28 / 45
- [x] HTML > HTML: hemos pasado el código HTML por el validador del W3C y ha devuelto los siguientes errores: 
   - Line 18: Element “a” not allowed as child of element “ul” in this context. (Suppressing further errors from this subtree.)
   - Line 21: Element “a” not allowed as child of element “ul” in this context. (Suppressing further errors from this subtree.)
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: El logo debe tener el atributo title.
- [x] HTML > MENÚ: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] HTML > MENÚ: Los enlaces deben tener el atributo `title`.
- [x] HTML > MENÚ: Los hijos directos de un `ul` solo puede ser un `li`.
- [x] HTML > MAIN: Necesitamos una etiqueta `h1`.
- [x] HTML > HTML: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > COLOR: El color del h1 debe ser blanco
- [x] CSS > COLOR: El color de los enlaces debe ser  4a4a4a
- [x] CSS > FONT-FAMILY: Usa la herencia, ponle la fuente Rubik al `body` para que la hereden el menú y el h1.
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > FONT-FAMILY: La fuente de los enlaces debe ser Rubik.
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING y MARGIN: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.menu { align-items: center }`, `.option { padding-right: 20px }`

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe todas las clases CSS en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

**Comment by Beatrizsobri** [comment]
@migueldelmazo Ya lo he corregido y subido! Si tienes tiempo, ¿podrías echarle un ojo? Porque hay cosas del checklist que ya las tenía hechas, entonces no sé si es que estaban mal hechas. 

¡¡Gracias por todo!!

**Comment by migueldelmazo** [comment]
Hola, he vuelto a pasar el auto corrector y me dice lo siguiente:

Score: 43 / 45
- [ ] En los enlaces estás poniendo `target="blanck"`, lo correcto sería `target="_blank".
- [ ] HTML > MENÚ: Los textos de los enlaces deben ser "Blog" y "Contacto" en el HTML. Debemos ponerlos en mayúsculas con CSS.
- [ ] HTML > HTML: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
